name: Deploy Supabase Edge Functions

on: [workflow_dispatch]

jobs:
  deployFunctions:
    runs-on: ubuntu-latest

    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}

    steps:
      - uses: actions/checkout@v3
      - uses: supabase/setup-cli@v1
      - run: supabase functions deploy --no-verify-jwt --project-ref=${{ secrets.SUPABASE_PROJECT_REF }} bot-test
