name: DEV Deployment

on: [push]

jobs:
  deployFunctions:
    runs-on: ubuntu-latest

    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}

    steps:
      - uses: actions/checkout@v3
      - uses: supabase/setup-cli@v1
      - run: supabase functions deploy --no-verify-jwt --project-ref=${{ secrets.SUPABASE_PROJECT_REF_DEV }} alfred_bot
      - run: supabase functions deploy --no-verify-jwt --project-ref=${{ secrets.SUPABASE_PROJECT_REF_DEV }} alfred_bot_cron

  setWebhook:
    runs-on: ubuntu-latest

    env:
      URL: https://api.telegram.org/bot${{ secrets.DEV_BOT_TOKEN }}/setWebhook?url=https://${{ secrets.SUPABASE_PROJECT_REF_DEV }}.functions.supabase.co/alfred_bot?secret=${{ secrets.DEV_BOT_TOKEN }}

    steps:
      - run: curl ${{ env.URL }}
